<P class=text><STRONG>BIM (Bachelor&nbsp;in Information &nbsp;Management)</STRONG><BR><BR>The Bachelor in Information management (BIM) is a four-year academic program. The Programme at National College Of Computer Studies, of Tribhuvan University, is designed to impart both theoretical foundation and practical knowledge in computer information system and IT. The course effectively assimilated two of the most popular disciplines-management and information technology. BIM has been designed to offer the students an opportunity to acquire the basic concepts and job oriented knowledge in computers with an accompanying flair in theory, tools and techniques of modern management. It is a rate opportunity to be graduate with two disciplines of equal competence.</P>
<P class=text>Specifically, the program aims:</P>
<UL class=text>
<LI>To provide a sound background in general courses. 
<LI>To familiarize students with the concepts and tools of management required in decision making. 
<LI>To equip students with the concepts and skills to use information technology for problem solving. 
<LI>To inculcate the students the skills required to meet the needs of industry for specialist management information system practioners and 
<LI>To help students learn to become socially responsible professionals and citizens.<BR></LI></UL>
<P class=text><STRONG>Career after BIM</STRONG><BR>Students after completion of the BIM programme are expected to work as programmers, system analysts, information analysts, database managers, network administrators, trainers, instructors, and salespersons in the field of software and hardware. Students may even go for higher studies in management, information technology and computer application.<BR></P>
<P class=text><STRONG>Potential Employers</STRONG><BR>A large number of organizations need competent and skilled professionals to analyse, design, implement and manage the information system to competitively run in today’s complex environment. Public or private, small or large, domestic or international, profit-making or non-profit making organization are expected to employ the outputs of the BIM programme.</P>
<P class=text><STRONG>BIM Course of Study</STRONG><BR>Students majoring in Business Computer Information Systems (BIM) gain valuable knowledge as they progress through a curriculum that prepares them well for their future careers.<BR></P>
