<?
	session_start();
	
	if (!$_SESSION["valid_user"])
		{
		// User not logged in, redirect to login page
		Header("Location: ../index.php");
		}

	include ("../include/db.php");
	$query = "Select * from tbl_members where id = $_SESSION[valid_id]";
	$result = mysql_query($query);
	$show = mysql_fetch_array($result);
		echo "<form action=\"member.php?MemberPageID=Option&Opt=ENF&Modify=Profile\" method=\"post\">\n";
		echo "<input type=\"hidden\" name=\"id\" value=\"$_SESSION[valid_id]\">\n"
			."<table width=\"500\" border=\"0\" cellspacing=\"1\" cellpadding=\"3\" class=\"table\">\n"
			."  <tr colspan=\"2\">\n" 
			."	<td class=\"text\"><strong><img src=\"../images/icons/profile.gif\" width=\"16\" height=\"16\" align=\"absmiddle\"> Modify My Profile: </strong><p></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Username</td>\n"
			."	<td class=\"text\"><strong>$show[username]</strong></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">First Name</td>\n"
			."	<td><input type=\"text\" name=\"firstname\" value=\"$show[firstname]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Middle Name</td>\n"
			."	<td><input type=\"text\" name=\"middlename\" value=\"$show[middlename]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Last Name</td>\n"
			."	<td><input type=\"text\" name=\"lastname\" value=\"$show[lastname]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Gender</td>\n"
			."	<td><select name=\"gender\" class=\"text_box\">\n"
			."		<option value=\"$show[gender]\" selected>$show[gender]</option>\n"
			."		<option>---------</option>\n"
			."		<option>Male</option>\n"
			."		<option>Female</option>\n"
			."	  </select></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Email</td>\n"
			."	<td><a href=\"mailto:$show[email]\">$show[email]</a></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Date of Birth</td>\n"
			."	<td class=\"text\"><input type=\"text\" name=\"dob\" value=\"$show[dob]\" class=\"text_box\"> Example: May 10, 1981</td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Education</td>\n"
			."	<td><select name=\"education\" class=\"text_box\">\n"
			."		<option value=\"$show[education]\" selected>$show[education]</option>\n"
			."		<option>---------------</option>\n"
			."		<option>SLC</option>\n"
			."		<option>Intermediate</option>\n"
			."		<option>Bachelor</option>\n"
			."		<option>Master</option>\n"
			."		<option>Others</option>\n"
			."	  </select> </td>\n"
			." </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Website</td>\n"
			."	<td><input name=\"website\" value=\"$show[website]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Telephone 1</td>\n"
			."	<td><input name=\"phone1\" value=\"$show[phone1]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n" 
			."	<td class=\"text\">Telephone 2</td>\n"
			."	<td><input name=\"phone2\" value=\"$show[phone2]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n"
			."	<td class=\"text\">Mobile</td>\n"
			."	<td><input name=\"mobile\" value=\"$show[mobile]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n"
			."	<td class=\"text\" valign=\"top\">Place</td>\n"
			."	<td><textarea name=\"address1\" cols=\"30\" rows=\"4\" class=\"text_box\">$show[address1]</textarea></td>\n"
			."  </tr>\n"
			."  <tr>\n"
			."	<td class=\"text\" valign=\"top\">Home Town</td>\n"
			."	<td><textarea name=\"address2\" cols=\"30\" rows=\"4\" class=\"text_box\">$show[address2]</textarea></td>\n"
			."  </tr>\n"
			."  <tr>\n"
			."	<td class=\"text\">City</td>\n"
			."	<td><input name=\"city\" value=\"$show[city]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n"
			."	<td class=\"text\">Country</td>\n"
			."	<td class=\"text\"><input name=\"country\" value=\"$show[country]\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."  <tr>\n"
			."	<td class=\"text\" valign=\"top\">Hobbies</td>\n"
			."	<td><textarea name=\"hobbies\" cols=\"30\" rows=\"4\" class=\"text_box\">$show[hobbies]</textarea></td>\n"
			."  </tr>\n"
			."  <tr>\n"
			."	<td class=\"text\">&nbsp;</td>\n"
			."	<td><input type=submit name=submit value=\"Modify\" class=\"text_box\"></td>\n"
			."  </tr>\n"
			."</table>";
?>