<table id="Table_01" width="778" border="0" cellpadding="0" cellspacing="0" align="center">
	<tr>
		<td width="243"><img src="<?=$Images;?>hd_01.gif" width="243" height="78" alt=""></td>
		<td width="535"><img src="<?=$Images;?>hd_04.gif" width="535" height="78" alt=""></td>
	</tr>
	<tr>
		<td colspan="2" class="bk_hdbar"><img src="<?=$Images;?>index_01.gif" width="2" height="7" /></td>
	</tr>
</table>
